name: test-env
channels:
  - conda-forge
  - bioconda
  - dranew
dependencies:
  - python>=3.09
  - samtools=1.22.1
  - star=2.7.11b
  - snakemake=9.11.6
  - bcl2fastq=2.19.0
  - setuptools
  - umi_tools=1.1.6