sample_sheet: tests/sample-sheet.csv
demux:
  r1: tests/R1.fastq.gz
  r2: tests/R2.fastq.gz
align:
  threads: 4
  genome_fasta_location: https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_49/GRCh38.primary_assembly.genome.fa.gz #url for downloading using wget
  genome_annotation_location: https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_49/gencode.v49.basic.annotation.gtf.gz #url for downloading using wget
  sjdb_overhang: 99
